language: php

php:
  - 5.5.9
  - 5.5
  - 5.6

sudo: false

install:
    - travis_retry composer install --no-interaction --prefer-source

before_script:
    - psql -c 'create database restaurant;' -U postgres
    - php artisan migrate --force

script:
    - vendor/bin/phpunit
