language: php

php:
  - 5.5.9
  - 5.5
  - 5.6

sudo: false

install:
    - pecl install PDO_PGSQL
    - composer install --no-interaction --prefer-source
env:
  global:
      - DB_CONNECTION=pgsql
      - DB_USERNAME=postgres
      - DB_HOST=localhost
      - DB_DATABASE=restaurant
      - APP_ENV=test

before_script:
    - psql -c 'create database restaurant;' -U postgres
    - php artisan migrate --force

script:
    - vendor/bin/phpunit
